[package]
name = "styleforce"
version = "0.0.3"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["abi3-py312", "extension-module"] }
marzano-gritmodule = { path = "../../vendor/gritql/crates/gritmodule" }
marzano-core = { path = "../../vendor/gritql/crates/core", default-features = false, features = [
    "non_wasm",
] }
marzano-language = { path = "../../vendor/gritql/crates/language" }
marzano-util = { path = "../../vendor/gritql/crates/util", features = ["finder"] }
grit-util = { path = "../../vendor/gritql/crates/grit-util" }
anyhow = "1.0.70"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
log = "0.4"
