[package]
name = "styleforce"
version = "0.0.3"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["abi3-py312", "extension-module"] }
marzano-core = { path = "../../vendor/gritql/crates/core", default-features = false, features = [
    "non_wasm",
] }
marzano-language = { path = "../../vendor/gritql/crates/language" }
marzano-util = { path = "../../vendor/gritql/crates/util" }
anyhow = "1.0.70"
